name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: buildjet-2vcpu-ubuntu-2204-arm

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker login --username unmanu --password ${{ secrets.GH_REGISTRY_TOKEN }} ghcr.io
        docker build . --file Dockerfile --tag ghcr.io/unmanu/pizzaaa:latest
        docker push ghcr.io/unmanu/pizzaaa:latest
